name: PHP Composer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build Docker image
      run: docker build -t my-php-app ./docker/php

    - name: Validate composer.json and composer.lock
      run: docker run --rm -v ${{ github.workspace }}:/var/www/html my-php-app composer validate --strict

    - name: Install dependencies
      run: docker run --rm -v ${{ github.workspace }}:/var/www/html my-php-app composer install --prefer-dist --no-progress --ignore-platform-req=ext-redis

    - name: Php code sniffer
      continue-on-error: false
      run: docker run --rm -v ${{ github.workspace }}:/var/www/html my-php-app composer run phpcs

    - name: Php stan
      continue-on-error: false
      run: docker run --rm -v ${{ github.workspace }}:/var/www/html my-php-app composer run phpstan

    - name: Tests
      continue-on-error: false
      run: docker run --rm -v ${{ github.workspace }}:/var/www/html my-php-app ./run_tests.sh
